### PR TITLE
fix: properly fallback in case of error/rejection of one Toot-ID getting method

### LINKED ISSUE #71: "Could not redirect due to an unexpected error" when attempting to boost a post on where unauthenticated access to public toots is not possible
## Bug description
When I click the Boost button to try to boost a remote post, I get an error notification from the addon that says "Could not redirect due to an unexpected error". Following the account does seem to work, however.

## Steps to reproduce

1. Open a remote post like [this one](https://types.pl/@emacsomancer/108431355656120911)
2. Click the "boost" icon.

### Actual behavior
A standard Mastodon popup appears, and a notification popup also appears:
noredirect

### Expected behavior
The simplified federation popup appears to confirm you want to boost the post. Or the post is opened in the user's local mastodon feed.

## System

Operating system and version: Gentoo linux 5.15.41
Browser and version: Firefox 91.10.0esr
Add-on version: 1.3

### PR DESCRIPTION
**Pull request by rugk**
To implement such a fallback mechanism the extension races two promises against each other here, which have these two methods implemented:
https://github.com/rugk/mastodon-simplified-federation/blob/e34050284bf2d614d694067ff32005eebd1f6427/src/background/modules/Detect/Mastodon.js#L164

[Promise.race](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/race) just has the [issue that it also rejects as soon as a promise rejects, i.e. errors](https://stackoverflow.com/questions/70747069/why-does-promise-race-fulfill-with-an-unfulfilled-promise).
That's actually not what we want. That works, as long as the success comes _before_ the error, but if the error is instant (which is nearly always the case here because the JSON API is faster than website scraping), then it fails.

We want to ignore errors. I.e. I found [something like this SO questions asks for](https://stackoverflow.com/questions/37234191/how-do-you-implement-a-racetosuccess-helper-given-a-list-of-promises), which [points to the modern browser-implemented solution](https://stackoverflow.com/a/60274215/5008962) called [`Promise.any`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/any).

Also needs bumping the Firefox version, but that is not a problem, as that version is really old enough to not be supported anymore. :D

---

_Also_ implemented a timeout for the API request, so it cannot be stale and hang around forever, which may be bad, too. (At some point we want to show the user an error, after all.)

Fixes #71

### CODE REVIEW

**Comment by rugk** [comment]
@viviicat Feel free to [try out the development version](https://github.com/TinyWebEx/common/blob/master/CONTRIBUTING.md#coding) and report back whether it/everything works/you like it or what may still be adjusted. And/Or review the code if needed.

Otherwise I'd merge that soon. :slightly_smiling_face: 

Of course I tested it by myself, and for me it worked with your toot URL.

File: src/common/modules/NetworkTools.js [hunk 1]
```diff
@@ -57,8 +58,24 @@ export function fetch(input, init = {}, ...args) {
         }
     }
 
+    // add timeout value if needed
+    // from https://stackoverflow.com/a/50101022/5008962
+    const abortController = new AbortController();
+    let abortTimeoutId;
+
+    if (!init.signal) {
+        abortTimeoutId = setTimeout(() => abortController.abort(), 5000);
```
Comment (rugk) [inline src/common/modules/NetworkTools.js:67]: I decided [against `AbortSignal.timeout`](https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal/timeout) as that is not widely implemented (only Firefox) and given https://github.com/rugk/mastodon-simplified-federation/issues/55 etc., this does not need to be adjusted then. It's also only a minor inconvenience in the code, so that's okay IMHO.

Though thinking about it, a note may be useful :D
```suggestion
        // replace with AbortSignal.timeout() if that is browser cross-compatible
        abortTimeoutId = setTimeout(() => abortController.abort(), 5000);
```
